import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Seed Store | The Place Where You Can Buy Any Kind of Seeds and Plants.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>To Product Page</h1>
        <Link href={"/products"}>
          <a>Seeds</a>
        </Link>
      </main>
    </div>
  )
}
